name: neo4j 
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'dm-tools/**'

jobs:
  build:
    name: neo4j
    runs-on: ubuntu-latest
    env:
      KUBECONFIG: '${{ github.workspace }}/.kube/kubeconfig'
      DDDMO: ${{ secrets.KUBECONFIG }}

    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Setup kubectl
      run: |
        mkdir -p '${{ github.workspace }}/.kube' \
          && echo "$DDDMO" > $KUBECONFIG
        sudo apt-get install -y neo4j-client
        kubectl -n dddmo port-forward svc/dddmo 7687:7687 &
        sleep 10
        cypher-shell -a 'neo4j://localhost:7687'

